// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqqamkrbcwzimwrkclb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcXFhbWtyYmN3emltd3JrY2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDgyODQsImV4cCI6MjA3MTk4NDI4NH0.Sr44SCYO2P9_bA2u-McKXkm1IWhYcaFIWZj-r_ZGdVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});